/**
 * Teslim Tutanagi PDF Olusturucu (Server-side)
 * jsPDF ile PDF olusturur ve Base64 olarak dondurur.
 */

import { jsPDF } from 'jspdf'
import 'jspdf-autotable'

// jspdf-autotable icin tip genisletmesi
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: Record<string, unknown>) => void
    lastAutoTable: { finalY: number }
  }
}

/** PDF DoS koruması: cok uzun stringleri kirp */
function clip(value: string | null | undefined, max: number): string {
  if (!value) return ''
  const s = String(value)
  return s.length > max ? s.slice(0, max - 1) + '…' : s
}

export type DocLocale = 'tr' | 'en' | 'de' | 'ar'

export interface DeliveryPdfData {
  documentNo: string
  deliveryDate: string
  receivedBy: string
  notes?: string | null
  schoolName?: string
  className?: string
  locale?: DocLocale
  orders: Array<{
    orderNumber: string
    studentName: string
    parentName: string
    totalAmount: number | string
    className?: string
    schoolName?: string
    items?: Array<{ name: string; quantity: number }>
  }>
}

export function generateDeliveryPdf(data: DeliveryPdfData): Buffer {
  const doc = new jsPDF()

  // --- Ceviriler (per-function) ---
  // NOT: jsPDF varsayilan fontlari Arapca glifleri dogru render edemez; bu yuzden
  // Arapca (ar) UI etiketleri icin Ingilizce'ye geri donulur (T.ar = T.en).
  const T_en = {
    title: 'DELIVERY RECEIPT',
    documentNo: 'Document No',
    deliveryDate: 'Delivery Date',
    receivedBy: 'Received By',
    totalPackages: 'Total Packages',
    school: 'School',
    class: 'Class',
    createdDate: 'Created Date',
    colNo: '#',
    colOrderNo: 'Order No',
    colStudent: 'Student',
    colParent: 'Parent',
    colContent: 'Content',
    colClass: 'Class',
    colAmount: 'Amount',
    totalAmount: 'Total Amount',
    notes: 'Notes',
    deliveredBy: 'Delivered By',
    deliveredTo: 'Received By',
    footer: 'This document was automatically generated by the School Supply System.',
  }
  const T = {
    tr: {
      title: 'TESLIM TUTANAGI',
      documentNo: 'Belge No',
      deliveryDate: 'Teslim Tarihi',
      receivedBy: 'Teslim Alan',
      totalPackages: 'Toplam Paket',
      school: 'Okul',
      class: 'Sinif',
      createdDate: 'Olusturma Tarihi',
      colNo: '#',
      colOrderNo: 'Siparis No',
      colStudent: 'Ogrenci',
      colParent: 'Veli',
      colContent: 'Icerik',
      colClass: 'Sinif',
      colAmount: 'Tutar',
      totalAmount: 'Toplam Tutar',
      notes: 'Notlar',
      deliveredBy: 'Teslim Eden',
      deliveredTo: 'Teslim Alan',
      footer: 'Bu belge Okul Tedarik Sistemi tarafindan otomatik olusturulmustur.',
    },
    en: T_en,
    de: {
      title: 'LIEFERSCHEIN',
      documentNo: 'Belegnummer',
      deliveryDate: 'Lieferdatum',
      receivedBy: 'Empfangen von',
      totalPackages: 'Pakete gesamt',
      school: 'Schule',
      class: 'Klasse',
      createdDate: 'Erstellungsdatum',
      colNo: '#',
      colOrderNo: 'Bestell-Nr.',
      colStudent: 'Schüler',
      colParent: 'Erziehungsberechtigter',
      colContent: 'Inhalt',
      colClass: 'Klasse',
      colAmount: 'Betrag',
      totalAmount: 'Gesamtbetrag',
      notes: 'Notizen',
      deliveredBy: 'Geliefert von',
      deliveredTo: 'Empfangen von',
      footer: 'Dieses Dokument wurde automatisch vom Schulbedarfssystem erstellt.',
    },
    // ar -> en fallback: jsPDF Arapca glif sinirlamasi
    ar: T_en,
  }
  const locale: DocLocale = data.locale ?? 'tr'
  const tr = T[locale] ?? T.tr

  // Baslik
  doc.setFontSize(18)
  doc.text(tr.title, 105, 20, { align: 'center' })

  // Belge bilgileri (DoS koruması: tum stringler clipped)
  doc.setFontSize(10)
  doc.text(`${tr.documentNo}: ${clip(data.documentNo, 50)}`, 14, 35)
  doc.text(`${tr.deliveryDate}: ${new Date(data.deliveryDate).toLocaleDateString('tr-TR')}`, 14, 42)
  doc.text(`${tr.receivedBy}: ${clip(data.receivedBy, 80)}`, 14, 49)
  doc.text(`${tr.totalPackages}: ${data.orders.length}`, 14, 56)

  if (data.schoolName) {
    doc.text(`${tr.school}: ${clip(data.schoolName, 80)}`, 120, 35)
  }
  if (data.className) {
    doc.text(`${tr.class}: ${clip(data.className, 50)}`, 120, 42)
  }

  doc.text(`${tr.createdDate}: ${new Date().toLocaleDateString('tr-TR')}`, 120, 49)

  // Cizgi
  doc.setLineWidth(0.5)
  doc.line(14, 62, 196, 62)

  // Ogrenci tablosu (DoS koruması: max 1000 satir + clipped strings)
  const limitedOrders = data.orders.slice(0, 1000)
  const tableData = limitedOrders.map((order, index) => [
    String(index + 1),
    clip(order.orderNumber, 30),
    clip(order.studentName, 60),
    clip(order.parentName, 50),
    clip(
      (order.items && order.items.length > 0)
        ? order.items.map(it => `${it.name} x${it.quantity}`).join(', ')
        : '-',
      200
    ),
    clip(order.className || data.className, 25),
    `${Number(order.totalAmount).toFixed(2)} TL`
  ])

  doc.autoTable({
    startY: 68,
    head: [[tr.colNo, tr.colOrderNo, tr.colStudent, tr.colParent, tr.colContent, tr.colClass, tr.colAmount]],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: [41, 128, 185],
      textColor: 255,
      fontSize: 9,
      fontStyle: 'bold'
    },
    bodyStyles: {
      fontSize: 8
    },
    columnStyles: {
      0: { cellWidth: 8, halign: 'center' },
      1: { cellWidth: 26 },
      2: { cellWidth: 28 },
      3: { cellWidth: 28 },
      4: { cellWidth: 45 },
      5: { cellWidth: 16 },
      6: { cellWidth: 22, halign: 'right' }
    },
    margin: { left: 14, right: 14 }
  })

  // Toplam tutar
  const finalY = doc.lastAutoTable.finalY + 10
  const totalAmount = data.orders.reduce((sum, o) => sum + Number(o.totalAmount), 0)
  doc.setFontSize(11)
  doc.text(`${tr.totalAmount}: ${totalAmount.toFixed(2)} TL`, 196, finalY, { align: 'right' })

  // Notlar (DoS koruması)
  if (data.notes) {
    doc.setFontSize(9)
    doc.text(`${tr.notes}: ${clip(data.notes, 500)}`, 14, finalY + 10)
  }

  // Imza alani
  const signatureY = finalY + (data.notes ? 30 : 20)
  doc.setLineWidth(0.3)
  doc.line(14, signatureY + 15, 80, signatureY + 15)
  doc.line(120, signatureY + 15, 196, signatureY + 15)
  doc.setFontSize(9)
  doc.text(tr.deliveredBy, 47, signatureY + 22, { align: 'center' })
  doc.text(tr.deliveredTo, 158, signatureY + 22, { align: 'center' })
  doc.text(clip(data.receivedBy, 50), 158, signatureY + 28, { align: 'center' })

  // Footer
  doc.setFontSize(7)
  doc.text(tr.footer, 105, 285, { align: 'center' })

  // Buffer olarak dondur
  const arrayBuffer = doc.output('arraybuffer')
  return Buffer.from(arrayBuffer)
}
