ALTER TABLE orders
  MODIFY status ENUM(
    'NEW','PAYMENT_PENDING','PAID','CONFIRMED','INVOICED',
    'SHIPPED','DELIVERED','COMPLETED','CANCELLED','REFUNDED','UNDELIVERED'
  ) NOT NULL DEFAULT 'NEW';
